"
SVG text
"
Class {
	#name : #ASText,
	#superclass : #ASShape,
	#category : #'Athens-SVG-Base'
}

{ #category : #accessing }
ASText >> font_family: aByteString [
]

{ #category : #accessing }
ASText >> font_size: aByteString [
]

{ #category : #'private - rendering' }
ASText >> setShapeOn: aCanvas [
]

{ #category : #accessing }
ASText >> x: aByteString [
]

{ #category : #accessing }
ASText >> y: aByteString [
]
